import type { Metadata } from "next";
import ThemeProvider from "../../themes/ThemeProvider";
import "./globals.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import CartContext from "../../components/cartcontext/CartProvider";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import { SidebarProvider } from "@/components/ui/sidebar";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("font-sans", geist.variable)}
    >
      {/* bg-gradient-to-r from-purple-300 to-gray-200 */}
      <body className="">

        <CartContext>
        {/* <ThemeProvider> */}
          <Navbar/>
     
          <main className="">
        {children}
        </main>
      
        {/* </ThemeProvider> */}
       </CartContext>
        <Footer/>
        </body>
    </html>
  );
}
