import type { Metadata } from "next";
import ThemeProvider from "../../themes/ThemeProvider";
import "./globals.css";
import Navbar from "../../components/Navbar";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={``}
    >
      <body className="bg-gradient-to-l from-purple-300 to-gray-200">
        {/* <ThemeProvider> */}
          <Navbar/>
        {children}
        {/* </ThemeProvider> */}
        </body>
    </html>
  );
}
